name: CI

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]
  merge_group:

env:
  FORCE_COLOR: 3

jobs:
  lint:
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      ADDRESS_ZIP_CODE_API_URL: ${{ secrets.ADDRESS_ZIP_CODE_API_URL }}
      ADDRESS_ZIP_CODE_API_KEY: ${{ secrets.ADDRESS_ZIP_CODE_API_KEY }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
      CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      APP_URL: ${{ secrets.APP_URL }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install deps
        run: bun install # --no-frozen-lockfile

      - name: Gen prisma client
        run: bun db:gen

      - name: Lint
        run: bun lint
